name: Sync files between branches

on:
  workflow_call:
    inputs:
      commit-message:
        required: false
        type: string
      files-path:
        required: true
        type: string
      target-branches:
        required: true
        type: string

    # secrets:
    #   token:
    #     required: true

jobs:
  Sync files:
    runs-on: ubuntu-latest

    env:
      # Colores para la terminal
      GREEN: '\033[0;32m'
      BOLD: '\033[1m'
      NC: '\033[0m' # No Color

      COMMIT_MESSAGE: "${{ inputs.commit-message}}"
      FILES_PATH: "${{ inputs.files-path }}"
      SOURCE_BRANCH: "${{ github.ref_name }}"
      SYNC_GROUP: "${{ inputs.target-branches}}"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Sync Folder Process
        run: |
          echo -e "${BOLD}Iniciando sincronización desde: $SOURCE_BRANCH${NC}"
          echo "Sincronizando archivos: $FILES_PATH"

          for branch in $SYNC_GROUP; do
            if [ "$branch" == "$SOURCE_BRANCH" ]; then continue;fi

            # 1. Creamos un grupo colapsable para cada rama
            echo "::group::Sincronizando con rama: $branch"

            if git checkout "$branch"; then
              # PASO CLAVE: Borramos el contenido actual en la rama destino para que 
              # si borraste un archivo en la origen, también se borre en la destino.
              rm -rf "$FILES_PATH"

              # Traemos la versión fresca de loa archivos desde la rama origen
              git checkout "$SOURCE_BRANCH" -- "$FILES_PATH"

              if ! git diff --cached --exit-code; then
                git commit -m "$COMMIT_MESSAGE | [ '$FILES_PATH' from $SOURCE_BRANCH ]"
                git push origin "$branch"

                # 2. Usamos un "notice" para que aparezca en el resumen general
                echo "::notice title=Éxito::Sincronización completada en rama $branch"
              else
                echo -e "${GREEN}Sin cambios pendientes en $branch.${NC}"
              fi
            else
                echo "::error::No se pudo encontrar la rama $branch"
            fi

            # 3. Cerramos el grupo
            echo "::endgroup::"
          done
