name: Sync Environment Cross Configurations

on:
  push:
    branches:
      - server
    paths:
      - ".github/workflows/**"
      - "README.md"

jobs:
  sync:
    strategy:
      # 'fail-fast: false' asegura que si falla la sincronización de neovim,
      # se intente de todas formas la del README.
      fail-fast: false
      matrix:
        include:
          - name: "Workflows"
            msg: "👷 Chore: sync Workflows folder"
            targets: "all"
            path: ".github/workflows"

          - name: "Documentation"
            msg: "📝 docs: Update README content "
            targets: "all"
            path: "README.md"

    uses: ./.github/workflows/sync-files.yaml
    with:
      files-path: ${{ matrix.path }}
      commit-message: ${{ matrix.msg }}
      target-branches: ${{ matrix.targets }}
